config.vm.define "attack-range-windows-server" do |config|
  VM_NAME_WIN_DC_CLIENT= "attack-range-windows-server"
  config.vm.box = "d1vious/windows2016"
  config.vm.hostname = "win-server"
  config.vm.boot_timeout = 600
  config.vm.communicator = "winrm"
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 300
  config.winrm.retry_limit = 20
  config.vm.network "forwarded_port", guest: 5985, host: 6001
  config.vm.network :private_network, ip: ENV["windows_server_private_ip"]

  config.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        ansible_port: 6001,
        ansible_winrm_scheme: 'http',
        splunk_indexer_ip: ENV["splunk_server_private_ip"],
        win_password: ENV["win_password"],
        splunk_uf_win_url: ENV["splunk_uf_win_url"],
        nxlog_url: ENV["nxlog_url"],
        install_dsp: ENV["install_dsp"],
        win_sysmon_url: ENV["win_sysmon_url"],
        win_sysmon_template: ENV["win_sysmon_template"],
        splunk_admin_password: ENV["splunk_admin_password"],
        windows_server_join_domain: ENV["windows_server_join_domain"],
        windows_domain_controller_private_ip: ENV["windows_domain_controller_private_ip"],
        run_demo: ENV["run_demo"],
        demo_scenario: ENV["demo_scenario"],
        capture_attack_data: ENV["capture_attack_data"],
        win_timezone: ENV["win_timezone"]
      }
      ansible.playbook = "../ansible/windows_dc_client.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{VM_NAME_WIN_DC_CLIENT}"
    vb.customize ["modifyvm", :id, "--memory", ENV["windows_server_memory"]
    vb.customize ["modifyvm", :id, "--cpus", ENV["windows_server_cpus"]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end
