config.vm.define "attack-range-splunk-server" do |config|
  VM_NAME= "attack-range-splunk-server"
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "#{VM_NAME}"
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest: 8000, host: 8000, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8089, host: 8089, protocol: "tcp"
  config.vm.network :private_network, ip: ENV["splunk_server_private_ip"]

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/splunk_server.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3",
        splunk_admin_password: ENV["splunk_admin_password"],
        splunk_url: ENV["splunk_url"],
        splunk_binary: ENV["splunk_binary"],
        s3_bucket_url: ENV["s3_bucket_url"],
        splunk_escu_app: ENV["splunk_escu_app"],
        splunk_asx_app: ENV["splunk_asx_app"],
        splunk_windows_ta: ENV["splunk_windows_ta"],
        splunk_cim_app: ENV["splunk_cim_app"],
        splunk_sysmon_ta: ENV["splunk_sysmon_ta"],
        caldera_password: ENV["caldera_password"],
        splunk_mltk_app: ENV["splunk_mltk_app"],
        splunk_bots_dataset: ENV["splunk_bots_dataset"],
        splunk_stream_app: ENV["splunk_stream_app"],
        splunk_python_app: ENV["splunk_python_app"],
        install_es: ENV["install_es"],
        install_mltk: ENV["install_mltk"],
        splunk_es_app: ENV["splunk_es_app"],
        phantom_app: ENV["phantom_app"],
        phantom_server: ENV["phantom_server"],
        phantom_server_private_ip: ENV["phantom_server_private_ip"],
        phantom_admin_password: ENV["phantom_admin_password"],
        splunk_security_essentials_app: ENV["splunk_security_essentials_app"],
        punchard_custom_visualization: ENV["punchard_custom_visualization"],
        status_indicator_custom_visualization: ENV["status_indicator_custom_visualization"],
        splunk_attack_range_dashboard: ENV["splunk_attack_range_dashboard"],
        timeline_custom_visualization: ENV["timeline_custom_visualization"],
        install_mission_control: ENV["install_mission_control"],
        mission_control_app: ENV["mission_control_app"],
        install_dsp: ENV["install_dsp"],
        dsp_client_cert_path: ENV["dsp_client_cert_path"],
        dsp_node: ENV["dsp_node"],
        splunk_server_private_ip: ENV["splunk_server_private_ip"],
        cloud_attack_range: '0'
      }
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{VM_NAME}"
    vb.customize ["modifyvm", :id, "--memory", ENV["splunk_server_memory"]]
    vb.customize ["modifyvm", :id, "--cpus", ENV["splunk_server_cpus"]]
  end
end
